# PBS configuration
queue: normalbw
# project: v45
walltime: 1:00:00
jobname: 1deg_core_nyf
ncpus: 252
mem: 500GB
# shortpath: /short/v45

# Model configuration
name: common
model: access-om2
input: /short/public/access-om2/input_rc/common_1deg_core
submodels:
    - name: atmosphere
      model: yatm
      exe: /short/public/access-om2/bin/yatm_347e0018.exe
      input: /short/public/access-om2/input_rc/yatm_1deg
      ncpus: 1

    - name: ocean
      model: mom
      exe: /short/public/access-om2/bin/fms_ACCESS-OM_7c8bb961.x
      input: /short/public/access-om2/input_rc/mom_1deg
      ncpus: 216

    - name: ice
      model: cice5
      exe: /short/public/access-om2/bin/cice_auscom_360x300_24p_a3632111.exe
      input: /short/public/access-om2/input_rc/cice_1deg
      ncpus: 24

# Collation
collate:
  walltime: 1:00:00
  mem: 30GB
  ncpus: 4
  queue: express
  restart: True
  exe: /short/public/access-om2/bin/mppnccombine

# Misc
runlog: True
stacksize: unlimited
mpirun: --mca orte_base_help_aggregate 0
qsub_flags: -W umask=027
platform:
    nodesize: 28

# DANGER! Do not uncomment this without checking the script is synching to the correct location!
# postscript: sync_data.sh
